# QUILL Configuration
kafka:
  brokers:
    - rwe-kafka:9092
  topic: "metrics"      # Replace with your Kafka topic
  group_id: "quill-consumer-group-%KAFKA_TOPIC%"

database:
  host: rwe-postgres
  port: 5432
  user: "quill"        # Replace with your DB user
  name: "quill"    # Replace with your DB name
  sslmode: disable

quill:
  batch_size: 20000          # Number of rows to batch before insert
  batch_timeout_seconds: 1s  # Max seconds to wait before inserting a partial batch
  channel_size: 4000
  kafka_offset_commit:
     every_messages: 1
     every_milliseconds: 1000

http:
  metrics_port: 8081

logging:
   level: TRACE

tracker:
   enabled: false

etcd:
  endpoints:
    - rwe-etcd:2379
  leaseTTLSeconds: 10
  etcdLeaderKey: 'quill/%KAFKA_TOPIC%/leader'

non_retriable_errors:
   - value: json_unmarshal_failed
     matched: equals
