kafka:
  brokers:
    - "10.117.209.25:9092"
    - "10.117.209.26:9092"
  topic: "metrics"      # Replace with your Kafka topic
  group_id: "quill-consumer-group-%KAFKA_TOPIC%"

database:
  host: "10.117.209.17"         # Replace with your TimescaleDB host
  port: 5433
  user: "postgres"        # Replace with your DB user
  name: "bess_data"    # Replace with your DB name
  sslmode: disable

quill:
  batch_size: 30000          # Number of rows to batch before insert
  batch_timeout_seconds: 1s  # Max seconds to wait before inserting a partial batch
  channel_size: 4000
  kafka_offset_commit:
     every_messages: 100
     every_milliseconds: 1000

http:
  metrics_port: 8084

tracker:
   enabled: false

etcd:
  endpoints:
    - 10.117.209.17:2379
    - 10.117.209.18:2379
    - 10.117.209.21:2379
  leaseTTLSeconds: 120
  etcdLeaderKey: 'quill/%KAFKA_TOPIC%/leader'

non_retriable_errors:
   - value: json_unmarshal_failed
     matched: contains

causing_failure_errors:
   - value: "Broker: Unknown member"
     matched: equals
